### ISSUE TITLE
Nested bullets only work in the preview

### ISSUE THREAD

**Issue by Ajedi32** [chmllr/NoteHub#24]
Source:

```markdown
This is a test

* Bullet 1
  * Nested
```

Result: https://www.notehub.org/2015/9/7/this-is-a-test

**Comment by chmllr** [comment]
Thanks for the bug report! I'm currently middle in migration of NoteHub to Node.js, so this will be fixed automatically, because only marked.js will be used in the future both on the client & server side.

**Comment by Ajedi32** [comment]
Sounds good, thanks for letting me know.

**Comment by chmllr** [comment]
Works as expected now.
