### ISSUE TITLE
How do you fork and host an instance?

### ISSUE THREAD

**Issue by ili-codes** [chmllr/NoteHub#32]
@chmllr Just had a question about the shut-down. 
I just started with GitHub in April and was wondering if someone knows how to get this running somewhere else? Would like to start an instance as this original instance is being taken down and I love this so much I'd like to make my own instance. So how can i do this? (e.g host on heroku, nitrous, or a webhost)

(remember, total no0b here)

**Comment by chmllr** [comment]
Hi some people suggested help, so the shutdown is delayed, at least for now.
I added instructions into the README.md file, how you can checkout and run NoteHub wherever you want. Please let me know if there are any issues with it.

**Comment by ghost** [comment]
.......................

**Comment by ghost** [comment]
......................

**Comment by chmllr** [comment]
I didn't use Heroku since I migrated to Node.js, but with some modifications it should run.

**Comment by ghost** [comment]
.....................
