### ISSUE TITLE
Slim down the workflow

### ISSUE THREAD

**Issue by tobireif** [chmllr/NoteHub#34]
Perhaps it would be possible to require "Accept Terms of Service" just once. (The data could perhaps be stored in a cookie?)

Same for the password - it would be great if I wouldn't have to enter it each time. Perhaps the fact that I'm allowed to edit the note I created could be stored in a cookie?

**Comment by chmllr** [comment]
Please help me understand the use case. Why would you enter the password or accept the TOS several times? If you are talking about editing the same note multiple times, then I'm not sure you are using the right tool for your needs. A static github page with versioning is more suitable for such a scenario, don't you think so?

**Comment by tobireif** [comment]
I'm writing the note online, at your site. The writing process looks like this: I add to / edit the note several times a day, for several days. Then when it's finished I might tweet it. Then there might be corrections to make based on feedback.

Having to enter the password each time is a hassle. (BTW, perhaps you want to ensure that the password gets concealed, eg by displaying it as stars.)

Other than that, NoteHub is a pretty good tool for my use case, I simply need an editable page with Markdown support. I don't need versioning for my use case.

**Comment by ili-codes** [comment]
@tobireif I agree with your password concealed idea and think it should be implemented very soon.
 
------

**Comment by tobireif** [comment]
@ili-codes Perhaps you want to create a separate issue for that.

**Comment by tobireif** [comment]
@chmllr P.S. Here's the note: https://notehub.org/2a5h6 .

**Comment by ili-codes** [comment]
@tobireif Thank you, I will
