### ISSUE TITLE
Character limit

### ISSUE THREAD

**Issue by Maxiride** [chmllr/NoteHub#36]
I tried to make a note with a folder tree generated with tree -H baseHREF on linux however when trying to post it (8162 words - but  TONS of them are just html code) i get the error Error: request entity too large.

I can understand that a limit is needed to avoid strain, but an improvement could be to show the remaining characters available.

Edit: Forgot to mention, the preview is generated instantly instead.

**Comment by Maxiride** [comment]
Meanwhile @chmllr may I ask which is the char limit? So I can write it down instead of going by trial and error to find it out ^^

**Comment by chmllr** [comment]
Thanks for reporting! NoteHub uses SQLite for persistence and doesn't apply any restrictions on the note length explicitly. So I assume your content is longer, that SQLite's maximum size of the TEXT type.

Also, I'd say you misuse NoteHub with this use case. Dropbox's Public folder would be more appropriate.

**Comment by Maxiride** [comment]
Yeah indeed I should use something else.

By the way I played around with your tool but I didn't managed to make a [suggested](http://www.silvabokis.com/squarespace-tips/how-to-create-hideshow-faqs-in-squarespace) code to hide\show blocks to work.

```<script>
    $(document).ready(function(){
    $('.markdown-block .sqs-block-content h2').css('cursor','pointer');
    $(".markdown-block .sqs-block-content h2").nextUntil("h2").slideToggle();
    $(".markdown-block .sqs-block-content h2").click(function() {$(this).nextUntil("h2").slideToggle();});
    });
    </script>```

Guess that the issue lies somewhere in relation to ".sqs" since that code was meant for the squarespace site. How should I make the call for markdown blocks in notehub?

**Comment by chmllr** [comment]
You are trying to create dynamic pages with JS functionality. This is not what NoteHub is designed for: all JavaScript code will be removed to keep the visitors safe. Notehub is for static Markdown/HTML pages only.
