### ISSUE TITLE
Prominently link the main page from the ".../edit" page

### ISSUE THREAD

**Issue by tobireif** [chmllr/NoteHub#38]
Google unfortunately brings
https://notehub.org/2a5h6/edit
instead of
https://notehub.org/2a5h6/ (at least it did so now).

It would be great if you could prominently link the corresponding main page from each ".../edit" page, in a top nav bar/link.

**Comment by chmllr** [comment]
I will block following *edit links through robots.

Thank you!

**Comment by tobireif** [comment]
Also *export URLs.

**Comment by chmllr** [comment]
Thanks for reporting. Closed with https://github.com/chmllr/NoteHub/commit/3810db4a613b9f969d0db24abd1134c085ceea65
