### ISSUE TITLE
get a list of notes?

### ISSUE THREAD

**Issue by omidfi** [chmllr/NoteHub#40]
hi, is there a way to get a list of all notes?

I tried to add a /all route, using Notes.findAll(), but it still required url

**Comment by omidfi** [comment]
Hi, I implemented this, a Basic pahe that lists all the Notes, with a filter to search by note titles. 

I can send a pull request if you like it.

**Comment by chmllr** [comment]
Thanks a lot, but such a list would expose notes supposed to be private. No note should be directly accessible without explicit sharing.

**Comment by omidfi** [comment]
I understand your point, but for our use case that was a fit as we are using it on our local network and we share notes together. 
Would you mind if I keep my own fork of this project with the feature? 

Here's the link to the fork that has the feature in case anyone else was interested: 
https://github.com/omidfi/NoteList

**Comment by chmllr** [comment]
Hi Omid! Sure, is a great idea actually. Feel free to pull from master to keep your brunch up to date.
