### ISSUE TITLE
"Password is wrong" destroys data

### ISSUE THREAD

**Issue by pdhixenbaugh** [chmllr/notehub#42]
If edits are made and an incorrect password or no password is entered into the box, the text changes are irrecoverable. "Password is wrong" should return the user to the previous screen where they can put in the correct password and publish the changes.

**Comment by chmllr** [comment]
Issue can be closed with ajax based form submission implemented in https://github.com/chmllr/notehub/commit/53f2dad4a2038f7b76eced635f718619eda0a077
