### ISSUE TITLE
Content lost on session expiration

### ISSUE THREAD

**Issue by rolfrb** [chmllr/NoteHub#44]
When you write content and have a long pause, your session will expire even though you are not logged in. When you click "Publish" you get a message that states "Sessions expired" and the content is lost. 

Since I wasn't logged in, I didn't even consider the possibility of a session. 

It would be nice if the sessions expiration either kept the content in an text field on the expiration page or if the service checked for session expiration before attempting to publishing.

**Comment by chmllr** [comment]
Thanks! Can you tell me please how long the page was open?

**Comment by rolfrb** [comment]
Looks like it was open for two days. So might not be the most common problem.
