### ISSUE TITLE
How can I delete a page?

### ISSUE THREAD

**Issue by hkjlweb** [chmllr/notehub#48]

**Comment by chmllr** [comment]
Delete the note text and save the note.

**Comment by hkjlweb** [comment]
Tried but not work. Got 404 error.
And the page seems being hacked with porn photo attached when open.

2017年9月21日 下午5:18 於 "Christian Müller" <notifications@github.com> 寫道：

**Comment by chmllr** [comment]
It did work. That's why 404. Will be improved soon.
