### ISSUE TITLE
[URGENT] Possible website hijack?

### ISSUE THREAD

**Issue by ipatrol** [chmllr/notehub#49]

**Comment by ipatrol** [comment]
I'm getting abusive, sexual pop-up ads from the site accessing from a mobile device.

**Comment by chmllr** [comment]
note Id?

**Comment by jesuslalvaro** [comment]
URGENT!!!! PLEASE
Porn in notes!!!
I use notehub at school!!

**Comment by chmllr** [comment]
@jesuslalvaro so please share the note id you visit at school? :)
