### ISSUE TITLE
Light theme?

### ISSUE THREAD

**Issue by toroidal-code** [chmllr/notehub#50]
The website used to have a very clean black-on-white layout, but this seems to have been swapped for white-on-grey. Is there any way to have the old theme be an option, such as including it in the URL slug?

**Comment by chmllr** [comment]
Could you give me please a bit more context to your request? Do you experience certain limitations to readability, etc? Thank you.

**Comment by ipatrol** [comment]
Yeah, I'd also agree that it hurts readability, especially on pages that have a lot of text inside of links. Requesting the ability to override the site's background color with per-note CSS?

**Comment by chmllr** [comment]
I changed the background color, because a lot of people used notes in iframes as a dynamic part of commercial static web pages. Implementing a CSS feature would give them even more options for abuse. If the link color is too dull though, I can definitely reconsider the color option.
