### ISSUE TITLE
Long lines of code don't wrap, run outside the container

### ISSUE THREAD

**Issue by sidola** [chmllr/notehub#51]
It seems long lines of code don't wrap like expected, and instead run outside the code container. This happens both for code that is indented with 4 spaces, and backtick wrapped code.

See example: https://notehub.org/id9m8

**Comment by chmllr** [comment]
Thanks! Fixed in https://github.com/chmllr/notehub/commit/cdb7f8c74dee9665d7bc345d272e4fe642863d23
