### ISSUE TITLE
enable api

### ISSUE THREAD

**Issue by leite** [chmllr/notehub#52]
Hi,

I was using the old notehub to store diff data from open street map (5-20kb every hour), but no longer works.

Can you enable API for posting notes?

Thanks.

**Comment by chmllr** [comment]
Sorry, but you understand that NoteHub is not a storage for your data?

**Comment by leite** [comment]
@chmllr ok, but still, no api in roadmap?

at least I can use your project in another host

**Comment by chmllr** [comment]
NoteHub had an API already, is was discontinued https://github.com/chmllr/notehub/issues/25
