### ISSUE TITLE
Porn ???

### ISSUE THREAD

**Issue by RichGriese** [chmllr/notehub#55]
Are you showing porn at the top of your pages on purpose?

**Comment by chmllr** [comment]
Which note exactly are you talking about?

**Comment by RichGriese** [comment]
Seems to happen when you put 3 or more url links in a note

**Comment by RichGriese** [comment]
Oh... I think you are adding this porn on purpose.

I was just looking at your TOS https://notehub.org/TOS.md and I notice...

Part 2. Use License, Section 3. create ‘hop’ notes containing a collection of links to external resources.

Which is exactly what I am trying to do. I can honestly say I never looked at your terms of service before.

Cheers!

**Comment by chmllr** [comment]
This is not "port", those are _context_ (!) depending ads :)
I have chosen to inject ads to notes violating the service to at least pay for the hosting, instead of just deleting the notes.

**Comment by RichGriese** [comment]
LOL... That's hysterical that your advertising vendor sees a list of links to podcasts on the history of Christianity, and evening Buddhism Dharma talks as a good place to serve up advertisements for child porn. Not sure if it says something about the ad agency, or Christianity & Buddhism.

**Comment by chmllr** [comment]
I need to check this. Please share the note or the content, so that I can reproduce it.

**Comment by RichGriese** [comment]
This is the content I had in the note...

## Active...

🔊 [The Bible Geek Podcast 18-004](http://recordings.talkshoe.com/TC-20430/TS-1236447.mp3) Today he's interviewing Bart Ehrman about his Book The Triumph of Christianity coming out on February 13

🎙 [Dharma talk - Preparing to meditate, by Thanissaro Bhikkhu (Geoffrey DeGraff)](http://dharmatalks.org/Archive/y2001/0104nZb1%20Preparing%20to%20Meditate.mp3)

<a href="#history" target="_self"><b><i>Links to "Older Stuff"</i></b></a>

<div style="float; margin-bottom:50px;"></div>
<hr>
<div style="float; margin-bottom:50px;"></div>

## Buddhism

Thanissaro Bhikkhu (Geoffrey DeGraff) Dharma Talks from January
- 🎙 [Short (Morning) Dhamma Talks](https://www.dhammatalks.org/mp3_short_index_current.html#1801)
- 🎙 [Evening Dhamma Talks](https://www.dhammatalks.org/mp3_index_current.html#1801)

[Noble Strategy, Essays on the Buddhist Path, by Thanissaro Bhikkhu](https://www.dhammatalks.org/Archive/Writings/Noble_Strategy.pdf) - The essays in this book present views on basic elements in the Buddhist path—the attitudes, concepts, and practices that lead to total freedom for the mind.

[The Wings to Awakening: An Anthology from the Pāli Canon, by Ṭhānissaro Bhikkhu](https://www.dhammatalks.org/books/Wings/Section0001.html) - An anthology of the Buddha’s teachings.

## Christianity

📺 Lecture Series : [Introduction To The New Testament History And Literature, Professor Dale Martin of Yale University](http://oyc.yale.edu/religious-studies/rlst-152?qt-course=2#qt-course)

🎙 Lecture Series : [The History of the Bible: The Making of the New Testament Canon, by Bart Ehrman of Chapel Hill University](https://archive.org/details/BartEhrman-TheHistoryOfTheBibleTheMakingOfTheNewTestamentCanon)

## Tech

[Webmention](https://indieweb.org/Webmention) is a web standard for mentions and conversations across the web, a powerful building block that is used for a growing federated network of comments, likes, reposts, and other rich interactions across the decentralized social web.

I'm also currently a big believer in [Feedly](http://feedly.com) (an RSS reader for consuming content), and [Twitter](http://twitter.com) for talking with people.

<div style="float; margin-bottom:50px;"></div>
<hr>
<div style="float; margin-bottom:50px;"></div>

<a id="history">

<h2 style="color:black;">Older Stuff...</h2>

🎙 [Episode 16 - Decline, Fall, or Transformation? Tides of History](https://dts.podtrac.com/redirect.mp3/rss.art19.com/episodes/5f769bcf-62e7-469f-a501-2c1b7a3bd465.mp3)

🎙 [Today's Morning dharma talk - Your primary duties, by Thanissaro Bhikkhu (Geoffrey DeGraff)](http://dharmatalks.org/Archive/shorttalks/y2018/180107(short)_Your_Primary_Duties.mp3)

🎙 [Today's Evening dharma talk - Skills for living & dying, by Thanissaro Bhikkhu (Geoffrey DeGraff)](http://dharmatalks.org/Archive/y2018/180107_Skills_for_Living_&_Dying.mp3)

🎙 [Episode 159 – Rest in Peace - The History of Byzantium Podcast](https://thehistoryofbyzantium.com/2017/12/22/episode-159-rest-in-peace/)

📺 [Lecture 25 Ecclesiastical Institutions: Unity, Martyrs, and Bishops](http://openmedia.yale.edu/projects/courses/spring09/rlst152/embed/rlst152_25_042009_emb.mp4)

🎙 [History in the making - liquidation](http://feedproxy.google.com/~r/squarespace/VuCD/~5/pC0rQi4cagM/ADL8807163374.mp3)

🎙 [The Waking Up Podcast #116 — AI: Racing Toward the Brink (Eliezer Yudkowsky)](http://wakingup.libsyn.com/116-ai-racing-toward-the-brink)

🎙 [237 Dissolution and Destruction – The History of England Podcast](https://thehistoryofengland.co.uk/2018/01/15/237-dissolution-and-destruction/)

🎙 [Ancient Greece Declassified Podcast: 16 Dialogue and Dialectic w/ MM McCabe (Philosophy, Plato, Socrates)](http://greecepodcast.libsyn.com/16-dialogue-and-dialectic-w-mm-mccabe-philosophy-plato-socrates)

🎙 [2 John – Sunday School Dropouts Podcast](http://sundayschooldropouts.lol/2-john/)

🎙 [238 The Fight Back – The History of England Podcast](https://thehistoryofengland.co.uk/2018/02/04/238-the-fight-back/)

🎙 [History in the Bible Podcast : 2.15 The Rise and Ruin of the Maccabeans](http://historyinthebible.libsyn.com/215-the-maccabean-century)
