### ISSUE TITLE
What is with the pornographic adverts?

### ISSUE THREAD

**Issue by Krelsis** [chmllr/NoteHub#57]
Just opened one of my previous pastes, noticed you've started using blockadblock, so naturally I disabled adblock, only to see that the adverts you have on your site are pornographic, asked other people to turn there's off to confirm, it seems they are seeing it too, can't you use something a little more appropriate for your ads? Some of us are trying to use your tool for legitimate purposes only to be thwarted by these inappropriate ads.

**Comment by chmllr** [comment]
Hi, thanks for reporting, could you please share the link to the note?

**Comment by RichGriese** [comment]
@Krelsis It seems if you have a number of URLs in the note NoteHub is now adding porn to the page. I've noticed self it can sometimes just take 3 URLs to turn the note into a porn site. Enjoy life!

**Comment by chmllr** [comment]
Actually the ads are context depended. Also, creating notes as hubs for links is prohibited by terms of service.

**Comment by RichGriese** [comment]
@chmllr Just trying to save @Krelsis some time. Months ago I found that a page I had created for links to resources on early Christian history was now showing porn. Sounds like he was coming across the same problem. Enjoy life!

**Comment by Krelsis** [comment]
Not exactly the best idea to make the ads content dependend, something that was SFW is now NSFW and can no longer be viewed safely :/

**Comment by chmllr** [comment]
@Krelsis no, you should not see _any_ ads in the first place if you did not violate TOS. That's why I am asking for a link to your note.

**Comment by Krelsis** [comment]
Welp, Looking at the TOS you're not allowed hop sites, which this is not, and you're not allowed to do anything unlawful nor attempt to modify or extend any of the software contained on the site, that considerred, I copy and pasted the contents of the notehub page to a new notehub, low and behold no ads this time, I'm not sure what flagged the first page but meh, Would excessive views flag it for adding adverts? The link to the old paste is : https://notehub.org/kbw28 and new is : https://notehub.org/8ybmt

**Comment by chmllr** [comment]
I closed the service completely.
