### ISSUE TITLE
Self Signed Certificate Error

### ISSUE THREAD

**Issue by TheDocTrier** [chmllr/NoteHub#58]
When visiting https://notehub.org , a self signed certificate is currently returned:

```
https://notehub.org/

The certificate is not trusted because it is self-signed.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

Certificate chain:

-----BEGIN CERTIFICATE-----
MIIDNTCCAh2gAwIBAgIFAY0sIhwwDQYJKoZIhvcNAQELBQAwFjEUMBIGA1UEAwwL
bm90ZWh1Yi5vcmcwHhcNMTgwNzEzMDUxMjQxWhcNMTkwNzEzMDUxMjQxWjAWMRQw
EgYDVQQDDAtub3RlaHViLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAKtg7/eO3ZfYoXOqpfilFbp1iNTRJXAEZdrYTfaIm7K167R9BdRR02pPMLK5
2FnnluhKl38UR17YorticmLoDBs10Tsf8oL9ZFFnzNG7GneI65UHzsFC6NV9Tpno
ldN8i4JErvW1QqXr4U6ce3jDCm/KkVJoCcJf4q9cEEBhjsToH6CqX7H7D/NtmwZN
cxN8ZMv2Z2ClZIR63n9tCPxkS226zI8se6mtBRV8Z9om8PynWd/JoumYRwHb5oBi
bSn3rP5pFI9tHSmVCxpsV7wNISFeta7ziEMJd24uS4QulGJsIPXRBrcOCqkmQcf3
9PTSQkeK8lpyvPP2T2kXWGQOV+ECAwEAAaOBiTCBhjAdBgNVHQ4EFgQUBpAlQKfz
PK96p5xF+9g5+0S/unMwHwYDVR0jBBgwFoAUBpAlQKfzPK96p5xF+9g5+0S/unMw
CQYDVR0TBAIwADA5BgNVHREEMjAwggtub3RlaHViLm9yZ4IQbWFpbC5ub3RlaHVi
Lm9yZ4IPd3d3Lm5vdGVodWIub3JnMA0GCSqGSIb3DQEBCwUAA4IBAQAs1NQ2xTmo
+jrK8zwPowZr6i1qJ92IQS6PTcrE5X9XZXG58BXaqs8zhGdvTq/o/STf/9GJk4UR
z0emctrIv5UavICVtIBpPUBs98XAPbWjSmDKVMqjxUo+04L98BIzf5cqmmzBSa8V
W8WXXgra1la2IX9KkgReMWpy3mgGhbSCXEDmXVl7uhnpgh9bdUJE8LxUZ3WQpfPJ
2vX/93JrKrhiLFCgdrfUOWGA2NxbcEy5vdVaTwpmGOh8dMD+dF5VPoa3fTK4KnpD
ceNvIQ1VSsvk3XrAHlQMGNag0XntbJj8rxuWZLd8RKoGXncZNj80W/QNrrJ5vDhi
38Q+u+nExWlY
-----END CERTIFICATE-----
```

I'm using Firefox 61.

**Comment by TheDocTrier** [comment]
Actually, it just changed to some spam looking website:

https://web.archive.org/web/20180713090226/https://notehub.org/

![spam_site_notehub](https://user-images.githubusercontent.com/9048525/42683125-43f25d9c-8641-11e8-9581-39b6e422af25.png)

**Comment by TheDocTrier** [comment]
Sorry for the rapid fire comments. It appears that the site now has a certificate from COMODO :
[notehuborg.txt](https://github.com/chmllr/notehub/files/2192039/notehuborg.txt)

Their seems to only be one external link (looks like a spam site, my antimalware blocked it):
http://laurensw.highepcs.hop.clickbank.net/?vtid=cquiza

**Comment by chmllr** [comment]
Hi, this project is not associated with notehub.org domain in any way.

**Comment by chmllr** [comment]
Sorry - important correction - not associated anymore.

**Comment by TheDocTrier** [comment]
@chmllr I'm sorry to hear that. I thought that it was a really good service. Was there any specific reason for shutting it down?

**Comment by chmllr** [comment]
I created NoteHub.org mainly as a small experiment 6 years ago and it was supposed to host markdown notes only. Unfortunately, it got very popular across the dark web and the overwhelming majority of notes are used as link hubs with illegal contents. I have no time to keep up with all the abuse reports.
