### ISSUE TITLE
Notehub.org is no more?

### ISSUE THREAD

**Issue by mrkishi** [chmllr/NoteHub#59]
Hey! First of all, thanks for such an useful project.

I just noticed notehub.org is no longer your domain. Are you still hosting the old notes somewhere or are they all gone?

In no way I expect you to keep providing that service for free, I'm just curious as to what happened and if we could do something to help.

Thank you!

**Comment by chmllr** [comment]
Please see this comment https://github.com/chmllr/notehub/issues/58#issuecomment-404805693

**Comment by chmllr** [comment]
Oh and your questions about notes — I have the archive, it won't be shared with anybody, but it is anyway 90% scam, at a very optimistic estimation.
